# ==========================================================
# Config Loss
# ==========================================================

loss:
  lambda_dssim: 0.2                  # trọng số SSIM trong loss tổng: (1-l)*L1 + l*(1-SSIM)
  use_lpips_eval: true
