# ==========================================================
# Config Renderer
# ==========================================================

renderer:
  backend: "gsplat"                  # "gsplat" | "diff_gaussian_rasterization"
  bg_color: [0, 0, 0]
  compute_cov3D_python: false
