# ==========================================================
# Config Optimizer + Training loop
# ==========================================================

optimizer:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001

train:
  sh_up_interval: 1000                # tăng SH degree mỗi N iter cho tới sh_degree tối đa
  save_interval: 5000
  eval_interval: 2000
  log_interval: 50
  checkpoint_dir: "./outputs/bts_scene_01/checkpoints"
